#!/usr/bin/env bash
set -e
exec > README.md
echo '# Thoughts?'
printf '```tree\n%s\n```\n' \
	"$(tree src -F --noreport | perl -pe 's|src||')"
while read -r i
	do printf '## `%s`\n```%s\n%s\n```\n' \
		"${i#src/}" \
		"${i##*.}" \
		"$(<"$i")"
done < <(find src -name \*.rs | sort)
